### PR TITLE
Replace MongoDB-/BSON-based JSON conversion with custom converter

### LINKED ISSUE #1: Add option to directly replace field with JSON-serialized value
This SMT seems super helpful, I was surprised something like this didn't exist already. However, there is one issue I have with it right now that would require some workarounds to bring our data into a nice shape.

Before the field value is converted to JSON, you wrap it with a struct first, which would transform a field called "nested" with a value like the following
```json
{
  "obj": { "a": "foo", "b": "bar" },
  "arr": [1, 2, 3]
}
```
into the string value
```json
"{\"nested\":{\"obj\":{\"a\":\"foo\",\"b\":\"bar\"},\"arr\":[1,2,3]}}"
```
that gets written back to the `nested` field in the output record. When this data now gets inserted into e.g. a Postgres JSONB column, I'd have to query the `obj.a` value like this:
```sql
SELECT nested -> 'nested' -> 'obj' -> 'a' FROM table;
```
That seems like unnecessary duplication to me and is a little unergonomic for the user. It would be nicer if they could just write
```sql
SELECT nested -> 'obj' -> 'a' FROM table;
```
Thus, an option to skip the struct-nesting step of the transformation would be much appreciated. I might give implementing it myself a go if that's welcome.

### PR DESCRIPTION
**Pull request by marvin-roesch**
Closes #1. This implements a custom converter to transform the Kafka Connect record into JSON. I have opted to go for the simplest possible conversion for each possible schema type.

I created this as a draft PR since there are two major decisions that biased this implementation, which we might want to revise:
 1. Types from the schema are not preserved. This means there is no way to convert the resulting JSON back into a Kafka Connect record with the same schema
 2.  `bytes` values are stored as Base64-encoded strings. There generally is no good way to store binary data in JSON, IMO, so this seemed like the most sensible option to me. An alternative would be to store the bytes as an escaped string.

Implementation-wise, I decided to use the [mjson](https://github.com/cesanta/mjson) library to produce the JSON values. This is a trade-off between increase in dependencies and simplicity in the implementation. Rather than a more complex library like Jackson or Gson, mjson only provides a barebones `Json` type. We could also produce JSON strings directly, but I think leaving potentially complex escaping logic for strings up to a library is a good compromise and keeps things simple.

Apart from removing obsolete dependencies, I have also move the `connect-transforms` dependency to the "provided" scope since that library should be on the classpath anyway and the removal can reduce fat JAR size further.

This obviously also constitutes a breaking change since we cannot support the old options anymore and the output format changed drastically.

Note that my Scala is a little rusty, so the code might not be the most idiomatic or elegant.

### CODE REVIEW

**Comment by kazanzhy** [comment]
Wow, that's amazing work!
Could you give me some time for review?

**Comment by kazanzhy** [comment]
Hi. @PaleoCrafter.
I looked at PR it's excellent, thanks for your time. During that time I got an idea.
What if we will keep both converters?
Personally, I like MongoDB extended mode, it keeps data types which makes it very powerful.
I thought that it might be one additional parameter like:
`transforms.torow.json.writer` can be either `bson` or `mjson`. I don't know how many developers are already using SMT, but It will be great to keep backward compatibility.
WDYT?

**Comment by marvin-roesch** [comment]
Thanks for the feedback, @kazanzhy! I can see the value of keeping both converters simultaneously. I'll make the required adjustments to make the writer configurable.

**Comment by marvin-roesch** [comment]
I have restructured the code to support different JSON writers and have re-introduced the BSON-based mode, @kazanzhy. The default is `bson`, so this should be fully backwards compatible.

**Review by kazanzhy — APPROVED** [review]

**Comment by marvin-roesch** [comment]
Thanks for merging, @kazanzhy! Can you give me a rough estimate on when you'll be pushing a new version to Confluent Hub so we can use this in production? :smile:

**Comment by kazanzhy** [comment]
Hi @PaleoCrafter. First of all, I want to thank you for your time.
So my plan contains the following steps:
- Run tests - Done
- Update README - Done
- Dependency check (`sbt dependencyCheck`) - Done
- Look dependency graph (`sbt dependencyBrowseGraph`) - Done
- Test using generated data - Done
- Create a new release - Done
- Contact the Confluent manager - Done
- Wait for deployment to Confluent Hub - In progress

**Comment by kazanzhy** [comment]
See the release:
https://github.com/kazanzhy/kafka-connect-transform-record2row/releases/tag/v0.2.0

And here's the result of the testing:
Screenshot from 2022-08-31 02-12-24

**Comment by kazanzhy** [comment]
@PaleoCrafter good news, the new version is ready. Last time it took a few days.
https://www.confluent.io/hub/kazanzhy/kafka-connect-transform-record2row

**Pull request merged**
